name: Staging Databse Backup

on:
  schedule:
    # Runs every day at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  call-backup:
    uses: moneylens-ws/.github/.github/workflows/backup-engine.yaml@task/update-db-backup-workflow
    with:
      environment: staging
    secrets:
      DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
      SUPABASE_STORAGE_URL: ${{ secrets.SUPABASE_STORAGE_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}