name: Production Database Backup

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  call-backup:
    uses: ./.github/workflows/backup-engine.yaml
    with:
      environment: production
      bucket: db-backups
    secrets:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_STORAGE_URL: ${{ secrets.SUPABASE_STORAGE_URL }}
