name: Staging Database Backup

on:
  schedule:
    # Runs every day at 02:00 UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  call-backup:
    uses: ./.github/workflows/backup-engine.yaml
    with:
      environment: staging
    secrets: inherit
